spring:
    security:
        oauth2:
            client:
                provider:
                    keycloak:
                        authorization-uri: ${KEYCLOAK_HOST}/realms/oauth2/protocol/openid-connect/auth
                        issuer-uri: ${KEYCLOAK_HOST}/realms/oauth2
                        jwk-set-uri: ${KEYCLOAK_HOST}/realms/oauth2/protocol/openid-connect/certs
                        token-uri: ${KEYCLOAK_HOST}/realms/oauth2/protocol/openid-connect/token
                        user-info-uri: ${KEYCLOAK_HOST}/realms/oauth2/protocol/openid-connect/userinfo
                        user-name-attribute: preferred_username
                registration:
                    keycloak:
                        authorization-grant-type: authorization_code
                        client-id: ${KEYCLOAK_CLIENT_ID}
                        client-name: ${KEYCLOAK_CLIENT_ID}
                        client-secret: ${KEYCLOAK_CLIENT_SECRET}
                        redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
                        scope: openid,email